### ISSUE TITLE
Grimm's Battlefield

### ISSUE THREAD

**Issue by MrRedBeard** [tskaufma/tskaufma.github.io#1]
Sorry I couldn't find another way to contact you. Grimm's Battlefield is great! Gets a little laggy after level 100 lol. I'd love to see it ported to mobile.

![20200810-16](https://user-images.githubusercontent.com/10256850/89820693-04d2b200-db13-11ea-8d5d-0492cb887c72.PNG)

**Comment by tskaufma** [comment]
Thank you for the feedback. I am glad you enjoy it!

Yes, the game isn't very optimized. It works for the lower levels but struggles the more there is to handle. It probably does not help that it's built on a game framework that hadn't kept up with the browsers (Crafty.js) and that I don't know too much game programming. I'd bet there are ways to fix it with enough effort.

I doubt I'd ever do a mobile port. While I am quite proud of creating Grimm's Battlefield, it's a project that has been complete for a while now. If I were to get into mobile programming in the future though, it could make a good project.

**Comment by MrRedBeard** [comment]
Totally understand. Thanks regardless its fun.
